# ============================================================================
# Starship Configuration - Clean, Fast, Essential
# ============================================================================

# Inserts a blank line between shell prompts
add_newline = true

# Timeout for commands executed by starship (in milliseconds)
command_timeout = 1000

# Scan timeout for files (in milliseconds)
scan_timeout = 30

# ============================================================================
# Format Configuration
# ============================================================================
format = """
[](fg:#a3aed2)\
$os\
$username\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$python\
$docker_context\
[](fg:#212736 bg:#1d2230)\
$cmd_duration\
$time\
[ ](fg:#1d2230)\
$line_break\
$character"""

# ============================================================================
# OS Module
# ============================================================================
[os]
style = "bg:#a3aed2 fg:#090c0c"
disabled = false

[os.symbols]
Arch = " "
Debian = " "
Fedora = " "
Linux = " "
Macos = " "
Ubuntu = " "
Windows = "󰍲 "

# ============================================================================
# User Module
# ============================================================================
[username]
show_always = true
style_user = "bg:#a3aed2 fg:#090c0c"
style_root = "bg:#a3aed2 fg:#090c0c"
format = '[ $user ]($style)'

# ============================================================================
# Directory Module
# ============================================================================
[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Essential directory substitutions only
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Desktop" = "󰧨 "
"~" = " "
".config" = " "
"dev" = " "
"src" = " "

# ============================================================================
# Git Modules
# ============================================================================
[git_branch]
symbol = " "
style = "bg:#394260 fg:#e3e5e5"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:#394260 fg:#e3e5e5"
format = '[$all_status$ahead_behind ]($style)'
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "?${count} "
modified = "!${count} "
staged = "+${count} "
deleted = "${count} "

# ============================================================================
# Programming Languages (Essential Only)
# ============================================================================
[nodejs]
symbol = " "
style = "bg:#212736 fg:#e3e5e5"
format = '[ $symbol($version) ]($style)'

[rust]
symbol = " "
style = "bg:#212736 fg:#e3e5e5"
format = '[ $symbol($version) ]($style)'

[golang]
symbol = " "
style = "bg:#212736 fg:#e3e5e5"
format = '[ $symbol($version) ]($style)'

[python]
symbol = " "
style = "bg:#212736 fg:#e3e5e5"
format = '[ $symbol($version) ]($style)'

# ============================================================================
# Docker Module
# ============================================================================
[docker_context]
symbol = " "
style = "bg:#212736 fg:#e3e5e5"
format = '[ $symbol$context ]($style)'
only_with_files = true

# ============================================================================
# Time Module
# ============================================================================
[time]
disabled = false
time_format = "%R"
style = "bg:#1d2230 fg:#e3e5e5"
format = '[ 󰥔 $time ]($style)'

# ============================================================================
# Character Module (Prompt Symbol)
# ============================================================================
[character]
success_symbol = '[](bold fg:#a3aed2)'
error_symbol = '[](bold fg:#ff6b6b)'
vicmd_symbol = '[](bold fg:#ffb347)'

# ============================================================================
# Command Duration Module
# ============================================================================
[cmd_duration]
min_time = 2_000
style = "bg:#1d2230 fg:#e3e5e5"
format = '[ 󰔚 $duration ]($style)'

# ============================================================================
# Disabled Modules (Performance & Clutter Reduction)
# ============================================================================
[package]
disabled = true

[memory_usage]
disabled = true

[battery]
disabled = true

[status]
disabled = true

[jobs]
disabled = true

[shell]
disabled = true

[shlvl]
disabled = true

[sudo]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = true

[terraform]
disabled = true