format = """
[](#9A348E)\
$os\
[](bg:#DA627D fg:#333333)\
$directory\
[](bg:#FCA17D fg:#333333)\
$git_branch\
$git_status\
[](bg:#86BBD8 fg:#333333)\
$golang\
$nodejs\
$rust\
$python\
[](bg:#06969A fg:#333333)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E fg:#333333)"
style_root = "bg:#9A348E fg:#333333)"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E fg:#333333)"
disabled = true # Disabled by default

[directory]
style = "bg:#DA627D fg:#333333)"
format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = "git:"
style = "bg:#FCA17D fg:#333333)"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D fg:#333333)"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "Go"
style = "bg:#86BBD8 fg:#333333)"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "No"
style = "bg:#86BBD8 fg:#333333)"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "Py"
style = "bg:#86BBD8 fg:#333333)"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8 fg:#333333)"
format = '[ $symbol ($version) ]($style)'

