# The current version of the config schema
version: 1

# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: ssh

# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: nvim

# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled

# Preference for editor-based interactive prompting. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prefer_editor_prompt: disabled

# A pager program to send command output to, e.g. "less". If blank, will refer to environment. Set the value to "cat" to disable the pager.
pager: less -FRX

# Aliases allow you to create nicknames for gh commands
aliases:
    # Checkout
    co: pr checkout
    
    # Pull request operations
    prc: pr create
    prs: pr status
    prv: pr view --web
    prl: pr list
    prm: pr merge
    
    # Issue operations
    ic: issue create
    is: issue status
    iv: issue view --web
    il: issue list
    
    # Repository operations
    rv: repo view --web
    rc: repo clone
    rf: repo fork
    
    # Workflow operations
    wl: workflow list
    wr: workflow run
    wv: workflow view
    
    # Browse
    b: browse
    
    # Quick actions
    sync: repo sync
    watch: repo view --web --branch main

# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:

# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:

# Whether to display labels using their RGB hex color codes in terminals that support truecolor. Supported values: enabled, disabled
color_labels: enabled

# Whether customizable, 4-bit accessible colors should be used. Supported values: enabled, disabled
accessible_colors: disabled

# Whether an accessible prompter should be used. Supported values: enabled, disabled
accessible_prompter: disabled

# Whether to use a animated spinner as a progress indicator. If disabled, a textual progress indicator is used instead. Supported values: enabled, disabled
spinner: enabled